# ╔════════════════════════════════════════════════════════════════════════════╗
#       This dockefile is generated by Automatic Dockerfile Generator v1.0
# ╚════════════════════════════════════════════════════════════════════════════╝
# ------------------ Build Stage -----------------------#

# React Aplication Dockerfile

# Avoid using latest tag in production
FROM node:latest AS build 

WORKDIR /app/

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build --prod
# ------------------ Production Stage ------------------#

# Nginx WebServer Dockerfile

# Avoid using latest tag in production
FROM nginx AS prod 

COPY --from=build /app/build/ /usr/share/nginx/html/

EXPOSE 80


