# ------------------ Build Stage -----------------------#


WORKDIR /app/

COPY package*.json ./ 

RUN --mount=type=cache,target=/root/.npm npm install \
    npm run build --prod

COPY . .

RUN npm run build --prod
# ------------------ Production Stage ------------------#

# Nginx WebServer Dockerfile

# Avoid using latest tag in production
FROM nginx:latest AS prod 


EXPOSE 80
