# Etapa 1: Compilar la aplicación Angular
FROM node:22 AS build

# Establece el directorio de trabajo
WORKDIR /usr/src/app/

# Copia los archivos de configuración
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Compila la aplicación
RUN npm run build --prod

# Etapa 2: Servir la aplicación Angular construida usando Apache httpd
FROM httpd

# Copia los archivos compilados desde la etapa de build
COPY --from=build /usr/src/app/dist/angular-example/browser/ /usr/local/apache2/htdocs/

# Copia el archivo de configuración de Apache
COPY my-httpd.conf /usr/local/apache2/conf/httpd.conf

# Exponer el puerto de Nginx
EXPOSE 80

# Apache ejecuta automáticamente su comando por defecto
