# Etapa 1: Compilar la aplicación Angular
FROM node:22 AS build

# Establece el directorio de trabajo
WORKDIR /usr/src/app/

# Copia los archivos de configuración
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Compila la aplicación
RUN npm run build --prod

# Etapa 2: Servir la aplicación Angular construida usando nginx
FROM nginx

# Copia los archivos compilados desde la etapa de build
COPY --from=build /usr/src/app/dist/angular-example /usr/share/nginx/html

# (Opcional) Copia el archivo de configuración de Nginx personalizado
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto de Nginx
EXPOSE 80

# Nginx ejecuta automáticamente su comando por defecto