# Windows requires the host OS version to match the container OS version. If you want to run a container based on a newer Windows build, 
# make sure you have an equivalent host build.

# This repo does not publish or maintain a latest tag. Please declare a specific tag when pulling or referencing images from this repo.
FROM mcr.microsoft.com/windows:ltsc2019
